// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	DepartmentUser string
	Departments    string
	IssueUser      string
	Issues         string
	ProjectUser    string
	Projects       string
	Users          string
}{
	DepartmentUser: "department_user",
	Departments:    "departments",
	IssueUser:      "issue_user",
	Issues:         "issues",
	ProjectUser:    "project_user",
	Projects:       "projects",
	Users:          "users",
}
